---
name: Lint Code Base

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Superlinter
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_GO: true
          VALIDATE_XML: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
