---
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
      packages: write
      deployments: write
    runs-on: ubuntu-latest
    name: Create releases
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Docker build
        run: make docker-build

      - name: Docker push
        run: make docker-publish
        env:
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Build binaries
        run: make build

      - name: Get the tag version
        id: get_version
        run: echo "::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/\.//g')"

      - name: Create release with binaries
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "dist/*"
          body: "Changelog for this release available [here.](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md#${{ steps.get_version.outputs.VERSION }})"
