on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Test
jobs:
  unit-test:
    name: Unit Tests
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Unit Tests
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.0.3
      with:
        file: ./coverage.out
        flags: ${{ runner.os }}

  compilation-test:
    name: Build test
    matrix:
      go-version: [1.15.x, 1.16.x, 1.17.x]
      os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Release test
        run: make build
