on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Test
jobs:
  test:
    name: junit2md
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Test
      run: go test ./...
